name: Deploy prod SHIELD dbt 

on:
  schedule:
     - cron: '0/3 * * * *'

# env:
#   DBT_SERVER_PROD: ${{ secrets.DBT_SERVER_PROD }}
#   DBT_PORT_PROD: ${{ secrets.DBT_PORT_PROD }}
#   DBT_USER_PROD: ${{ secrets.DBT_USER_PROD }}
#   DBT_PASSWORD_PROD: ${{ secrets.DBT_PASSWORD_PROD }}
#   DBT_DATABASE_PROD: ${{ secrets.DBT_DATABASE_PROD }}
#   DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
env:
  DBT_SERVER_TEST: ${{ secrets.DBT_SERVER_TEST }}
  DBT_PORT_TEST: ${{ secrets.DBT_PORT_TEST }}
  DBT_USER_TEST: ${{ secrets.DBT_USER_TEST }}
  DBT_PASSWORD_TEST: ${{ secrets.DBT_PASSWORD_TEST }}
  DBT_DATABASE_TEST: ${{ secrets.DBT_DATABASE_TEST }}
  DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          # dbt deps --profiles-dir ./profiles/ --target prod
          dbt deps --profiles-dir ./profiles/ --target test
         

      - name: Run dbt seeds
        run: |
          # dbt seed --profiles-dir ./profiles/ --target prod --full-refresh
          dbt seed --profiles-dir ./profiles/ --target test --full-refresh
          
          
      - name: Run dbt models
        run: |
          # dbt run --profiles-dir ./profiles/ --target prod
          dbt run --profiles-dir ./profiles/ --target test
         

      - name: Run dbt tests
        run: |
          # dbt test --profiles-dir ./profiles/ --target prod
          dbt test --profiles-dir ./profiles/ --target test
       

          
