name: Deploy SHIELD dbt to Prod and Test

on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [test, prod]
    env:
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_SERVER_TEST: ${{ secrets.DBT_SERVER_TEST }}
      DBT_PORT_TEST: ${{ secrets.DBT_PORT_TEST }}
      DBT_USER_TEST: ${{ secrets.DBT_USER_TEST }}
      DBT_PASSWORD_TEST: ${{ secrets.DBT_PASSWORD_TEST }}
      DBT_DATABASE_TEST: ${{ secrets.DBT_DATABASE_TEST }}
      DBT_SERVER_DEV: ${{ secrets.DBT_SERVER_DEV }}
      DBT_PORT_DEV: ${{ secrets.DBT_PORT_DEV }}
      DBT_USER_DEV: ${{ secrets.DBT_USER_DEV }}
      DBT_PASSWORD_DEV: ${{ secrets.DBT_PASSWORD_DEV }}
      DBT_DATABASE_DEV: ${{ secrets.DBT_DATABASE_DEV }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          dbt deps --profiles-dir ./profiles/ --target ${{ matrix.environment }}

      - name: Run dbt seeds for ${{ matrix.environment }}
        run: |
          dbt seed --profiles-dir ./profiles/ --target ${{ matrix.environment }} --full-refresh

      - name: Run dbt models for ${{ matrix.environment }}
        run: |
          dbt run --profiles-dir ./profiles/ --target ${{ matrix.environment }}

      - name: Run dbt tests for ${{ matrix.environment }}
        run: |
          dbt test --profiles-dir ./profiles/ --target ${{ matrix.environment }}
      
          
