version: 2
sources:
  - name: central_raw_sari_ili
    database: shield
    schema: central_raw_sari_ili
    tables:
      - name: sari_ili_data
        description: This table contains raw data for SARI-ILI
  - name: central_raw_khis
    database: shield
    schema: central_raw_khis
    tables:
      - name: moh_505
        description: This table contains raw data for MOH 505 form
  - name: central_raw_mdharura
    database: shield
    schema: central_raw_mdharura
    tables:
      - name: mdharura_ebs_linelist
        description: This table contains raw data for M-dharura app
      - name: mdharura_ebs_aggregate
        description: This table contains raw aggregate data for M-dharura app
  - name: staging
    database: shield
    schema: staging 
    tables:
      - name: stg_ebridge_output
        description: This table contains raw data from the e-bridge ML model 
      - name: stg_ebridge_output_actual_predicted
  - name: central_raw_mortality
    database: shield
    schema: central_raw_mortality 
    tables:
      - name: mortality_surveillance
        description: This table contains raw data for the mortality surveillance
  - name: central_raw_afi
    database: shield
    schema: central_raw_afi 
    tables:
      - name: screening
        description: This table contains raw data for AFI screening
      - name: lab_results
      - name: malaria_rdt
      - name: enroll_and_household_info
      - name: history_and_physical_exam
      - name: afi_tac_results
      - name: physical_abstraction
      - name: sample_collection
      - name: leptospirosis_rdt
      - name: npop_swab
      - name: sarscov_merged_results
      - name: nasal_swab
      - name: throat_swab
      - name: clinical_course_outcome
  - name: central_raw_krcs
    database: shield
    schema: central_raw_krcs
    tables:
      - name: cbs
        description: This table contains raw data for Red Cross CBS
  - name: central_raw_ears
    database: shield
    schema: central_raw_ears
    tables:
      - name: veoc_covid_linelist_results
